version: "3.9"
services:  
  mysql:
    image: mysql:latest
    cap_add:
      - "SYS_NICE"
    restart: always
    container_name: ascan_subscriptions_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'p4ss@word'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./database/schemas.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_logs:/var/log/rabbitmq
    networks:
        - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
    
volumes:
  db:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local